'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioProveedor
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioProveedor.IProveedorWcf")>  _
    Public Interface IProveedorWcf
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IProveedorWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodos() As Entidades.ProveedorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IProveedorWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/Insertar", ReplyAction:="http://tempuri.org/IProveedorWcf/InsertarResponse")>  _
        Function Insertar(ByVal proveedorENT As Entidades.ProveedorENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/Insertar", ReplyAction:="http://tempuri.org/IProveedorWcf/InsertarResponse")>  _
        Function InsertarAsync(ByVal proveedorENT As Entidades.ProveedorENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/Actualizar", ReplyAction:="http://tempuri.org/IProveedorWcf/ActualizarResponse")>  _
        Function Actualizar(ByVal proveedorENT As Entidades.ProveedorENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/Actualizar", ReplyAction:="http://tempuri.org/IProveedorWcf/ActualizarResponse")>  _
        Function ActualizarAsync(ByVal proveedorENT As Entidades.ProveedorENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/SeleccionarProveedor", ReplyAction:="http://tempuri.org/IProveedorWcf/SeleccionarProveedorResponse")>  _
        Function SeleccionarProveedor() As Entidades.ProveedorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/SeleccionarProveedor", ReplyAction:="http://tempuri.org/IProveedorWcf/SeleccionarProveedorResponse")>  _
        Function SeleccionarProveedorAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/BuscarProveedor", ReplyAction:="http://tempuri.org/IProveedorWcf/BuscarProveedorResponse")>  _
        Function BuscarProveedor(ByVal campo As String, ByVal texto As String) As Entidades.ProveedorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProveedorWcf/BuscarProveedor", ReplyAction:="http://tempuri.org/IProveedorWcf/BuscarProveedorResponse")>  _
        Function BuscarProveedorAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ProveedorENT())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IProveedorWcfChannel
        Inherits ServicioProveedor.IProveedorWcf, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ProveedorWcfClient
        Inherits System.ServiceModel.ClientBase(Of ServicioProveedor.IProveedorWcf)
        Implements ServicioProveedor.IProveedorWcf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SeleccionarTodos() As Entidades.ProveedorENT() Implements ServicioProveedor.IProveedorWcf.SeleccionarTodos
            Return MyBase.Channel.SeleccionarTodos
        End Function
        
        Public Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT()) Implements ServicioProveedor.IProveedorWcf.SeleccionarTodosAsync
            Return MyBase.Channel.SeleccionarTodosAsync
        End Function
        
        Public Function Insertar(ByVal proveedorENT As Entidades.ProveedorENT) As Integer Implements ServicioProveedor.IProveedorWcf.Insertar
            Return MyBase.Channel.Insertar(proveedorENT)
        End Function
        
        Public Function InsertarAsync(ByVal proveedorENT As Entidades.ProveedorENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioProveedor.IProveedorWcf.InsertarAsync
            Return MyBase.Channel.InsertarAsync(proveedorENT)
        End Function
        
        Public Function Actualizar(ByVal proveedorENT As Entidades.ProveedorENT) As Integer Implements ServicioProveedor.IProveedorWcf.Actualizar
            Return MyBase.Channel.Actualizar(proveedorENT)
        End Function
        
        Public Function ActualizarAsync(ByVal proveedorENT As Entidades.ProveedorENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioProveedor.IProveedorWcf.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(proveedorENT)
        End Function
        
        Public Function SeleccionarProveedor() As Entidades.ProveedorENT() Implements ServicioProveedor.IProveedorWcf.SeleccionarProveedor
            Return MyBase.Channel.SeleccionarProveedor
        End Function
        
        Public Function SeleccionarProveedorAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT()) Implements ServicioProveedor.IProveedorWcf.SeleccionarProveedorAsync
            Return MyBase.Channel.SeleccionarProveedorAsync
        End Function
        
        Public Function BuscarProveedor(ByVal campo As String, ByVal texto As String) As Entidades.ProveedorENT() Implements ServicioProveedor.IProveedorWcf.BuscarProveedor
            Return MyBase.Channel.BuscarProveedor(campo, texto)
        End Function
        
        Public Function BuscarProveedorAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ProveedorENT()) Implements ServicioProveedor.IProveedorWcf.BuscarProveedorAsync
            Return MyBase.Channel.BuscarProveedorAsync(campo, texto)
        End Function
    End Class
End Namespace
