'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioContacto
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioContacto.IContactoWcf")>  _
    Public Interface IContactoWcf
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodos() As Entidades.ContactoENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ContactoENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarContacto", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarContactoResponse")>  _
        Function SeleccionarContacto(ByVal ProveedorId As Integer) As Entidades.ContactoENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarContacto", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarContactoResponse")>  _
        Function SeleccionarContactoAsync(ByVal ProveedorId As Integer) As System.Threading.Tasks.Task(Of Entidades.ContactoENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/Insertar", ReplyAction:="http://tempuri.org/IContactoWcf/InsertarResponse")>  _
        Function Insertar(ByVal contactoENT As Entidades.ContactoENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/Insertar", ReplyAction:="http://tempuri.org/IContactoWcf/InsertarResponse")>  _
        Function InsertarAsync(ByVal contactoENT As Entidades.ContactoENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/Actualizar", ReplyAction:="http://tempuri.org/IContactoWcf/ActualizarResponse")>  _
        Function Actualizar(ByVal contactoENT As Entidades.ContactoENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/Actualizar", ReplyAction:="http://tempuri.org/IContactoWcf/ActualizarResponse")>  _
        Function ActualizarAsync(ByVal contactoENT As Entidades.ContactoENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarProveedor", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarProveedorResponse")>  _
        Function SeleccionarProveedor() As Entidades.ProveedorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/SeleccionarProveedor", ReplyAction:="http://tempuri.org/IContactoWcf/SeleccionarProveedorResponse")>  _
        Function SeleccionarProveedorAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/BuscarContacto", ReplyAction:="http://tempuri.org/IContactoWcf/BuscarContactoResponse")>  _
        Function BuscarContacto(ByVal campo As String, ByVal texto As String) As Entidades.ContactoENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IContactoWcf/BuscarContacto", ReplyAction:="http://tempuri.org/IContactoWcf/BuscarContactoResponse")>  _
        Function BuscarContactoAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ContactoENT())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IContactoWcfChannel
        Inherits ServicioContacto.IContactoWcf, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ContactoWcfClient
        Inherits System.ServiceModel.ClientBase(Of ServicioContacto.IContactoWcf)
        Implements ServicioContacto.IContactoWcf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SeleccionarTodos() As Entidades.ContactoENT() Implements ServicioContacto.IContactoWcf.SeleccionarTodos
            Return MyBase.Channel.SeleccionarTodos
        End Function
        
        Public Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ContactoENT()) Implements ServicioContacto.IContactoWcf.SeleccionarTodosAsync
            Return MyBase.Channel.SeleccionarTodosAsync
        End Function
        
        Public Function SeleccionarContacto(ByVal ProveedorId As Integer) As Entidades.ContactoENT() Implements ServicioContacto.IContactoWcf.SeleccionarContacto
            Return MyBase.Channel.SeleccionarContacto(ProveedorId)
        End Function
        
        Public Function SeleccionarContactoAsync(ByVal ProveedorId As Integer) As System.Threading.Tasks.Task(Of Entidades.ContactoENT()) Implements ServicioContacto.IContactoWcf.SeleccionarContactoAsync
            Return MyBase.Channel.SeleccionarContactoAsync(ProveedorId)
        End Function
        
        Public Function Insertar(ByVal contactoENT As Entidades.ContactoENT) As Integer Implements ServicioContacto.IContactoWcf.Insertar
            Return MyBase.Channel.Insertar(contactoENT)
        End Function
        
        Public Function InsertarAsync(ByVal contactoENT As Entidades.ContactoENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioContacto.IContactoWcf.InsertarAsync
            Return MyBase.Channel.InsertarAsync(contactoENT)
        End Function
        
        Public Function Actualizar(ByVal contactoENT As Entidades.ContactoENT) As Integer Implements ServicioContacto.IContactoWcf.Actualizar
            Return MyBase.Channel.Actualizar(contactoENT)
        End Function
        
        Public Function ActualizarAsync(ByVal contactoENT As Entidades.ContactoENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioContacto.IContactoWcf.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(contactoENT)
        End Function
        
        Public Function SeleccionarProveedor() As Entidades.ProveedorENT() Implements ServicioContacto.IContactoWcf.SeleccionarProveedor
            Return MyBase.Channel.SeleccionarProveedor
        End Function
        
        Public Function SeleccionarProveedorAsync() As System.Threading.Tasks.Task(Of Entidades.ProveedorENT()) Implements ServicioContacto.IContactoWcf.SeleccionarProveedorAsync
            Return MyBase.Channel.SeleccionarProveedorAsync
        End Function
        
        Public Function BuscarContacto(ByVal campo As String, ByVal texto As String) As Entidades.ContactoENT() Implements ServicioContacto.IContactoWcf.BuscarContacto
            Return MyBase.Channel.BuscarContacto(campo, texto)
        End Function
        
        Public Function BuscarContactoAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ContactoENT()) Implements ServicioContacto.IContactoWcf.BuscarContactoAsync
            Return MyBase.Channel.BuscarContactoAsync(campo, texto)
        End Function
    End Class
End Namespace
