'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioServidor
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioServidor.IServidorWcf")>  _
    Public Interface IServidorWcf
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IServidorWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodos() As Entidades.ServidorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IServidorWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ServidorENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/Insertar", ReplyAction:="http://tempuri.org/IServidorWcf/InsertarResponse")>  _
        Function Insertar(ByVal servidorENT As Entidades.ServidorENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/Insertar", ReplyAction:="http://tempuri.org/IServidorWcf/InsertarResponse")>  _
        Function InsertarAsync(ByVal servidorENT As Entidades.ServidorENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/Actualizar", ReplyAction:="http://tempuri.org/IServidorWcf/ActualizarResponse")>  _
        Function Actualizar(ByVal servidorENT As Entidades.ServidorENT) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/Actualizar", ReplyAction:="http://tempuri.org/IServidorWcf/ActualizarResponse")>  _
        Function ActualizarAsync(ByVal servidorENT As Entidades.ServidorENT) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/BuscarServidor", ReplyAction:="http://tempuri.org/IServidorWcf/BuscarServidorResponse")>  _
        Function BuscarServidor(ByVal campo As String, ByVal texto As String) As Entidades.ServidorENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidorWcf/BuscarServidor", ReplyAction:="http://tempuri.org/IServidorWcf/BuscarServidorResponse")>  _
        Function BuscarServidorAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ServidorENT())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServidorWcfChannel
        Inherits ServicioServidor.IServidorWcf, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServidorWcfClient
        Inherits System.ServiceModel.ClientBase(Of ServicioServidor.IServidorWcf)
        Implements ServicioServidor.IServidorWcf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SeleccionarTodos() As Entidades.ServidorENT() Implements ServicioServidor.IServidorWcf.SeleccionarTodos
            Return MyBase.Channel.SeleccionarTodos
        End Function
        
        Public Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ServidorENT()) Implements ServicioServidor.IServidorWcf.SeleccionarTodosAsync
            Return MyBase.Channel.SeleccionarTodosAsync
        End Function
        
        Public Function Insertar(ByVal servidorENT As Entidades.ServidorENT) As Integer Implements ServicioServidor.IServidorWcf.Insertar
            Return MyBase.Channel.Insertar(servidorENT)
        End Function
        
        Public Function InsertarAsync(ByVal servidorENT As Entidades.ServidorENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioServidor.IServidorWcf.InsertarAsync
            Return MyBase.Channel.InsertarAsync(servidorENT)
        End Function
        
        Public Function Actualizar(ByVal servidorENT As Entidades.ServidorENT) As Integer Implements ServicioServidor.IServidorWcf.Actualizar
            Return MyBase.Channel.Actualizar(servidorENT)
        End Function
        
        Public Function ActualizarAsync(ByVal servidorENT As Entidades.ServidorENT) As System.Threading.Tasks.Task(Of Integer) Implements ServicioServidor.IServidorWcf.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(servidorENT)
        End Function
        
        Public Function BuscarServidor(ByVal campo As String, ByVal texto As String) As Entidades.ServidorENT() Implements ServicioServidor.IServidorWcf.BuscarServidor
            Return MyBase.Channel.BuscarServidor(campo, texto)
        End Function
        
        Public Function BuscarServidorAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ServidorENT()) Implements ServicioServidor.IServidorWcf.BuscarServidorAsync
            Return MyBase.Channel.BuscarServidorAsync(campo, texto)
        End Function
    End Class
End Namespace
