'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioLogin
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioLogin.IUsuarioWcf")>  _
    Public Interface IUsuarioWcf
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioWcf/Ingresar", ReplyAction:="http://tempuri.org/IUsuarioWcf/IngresarResponse")>  _
        Function Ingresar(ByVal usuarioENT As Entidades.UsuarioENT) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioWcf/Ingresar", ReplyAction:="http://tempuri.org/IUsuarioWcf/IngresarResponse")>  _
        Function IngresarAsync(ByVal usuarioENT As Entidades.UsuarioENT) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioWcf/SelecccionarUsuario", ReplyAction:="http://tempuri.org/IUsuarioWcf/SelecccionarUsuarioResponse")>  _
        Function SelecccionarUsuario() As Entidades.UsuarioENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioWcf/SelecccionarUsuario", ReplyAction:="http://tempuri.org/IUsuarioWcf/SelecccionarUsuarioResponse")>  _
        Function SelecccionarUsuarioAsync() As System.Threading.Tasks.Task(Of Entidades.UsuarioENT())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUsuarioWcfChannel
        Inherits ServicioLogin.IUsuarioWcf, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UsuarioWcfClient
        Inherits System.ServiceModel.ClientBase(Of ServicioLogin.IUsuarioWcf)
        Implements ServicioLogin.IUsuarioWcf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Ingresar(ByVal usuarioENT As Entidades.UsuarioENT) As Boolean Implements ServicioLogin.IUsuarioWcf.Ingresar
            Return MyBase.Channel.Ingresar(usuarioENT)
        End Function
        
        Public Function IngresarAsync(ByVal usuarioENT As Entidades.UsuarioENT) As System.Threading.Tasks.Task(Of Boolean) Implements ServicioLogin.IUsuarioWcf.IngresarAsync
            Return MyBase.Channel.IngresarAsync(usuarioENT)
        End Function
        
        Public Function SelecccionarUsuario() As Entidades.UsuarioENT() Implements ServicioLogin.IUsuarioWcf.SelecccionarUsuario
            Return MyBase.Channel.SelecccionarUsuario
        End Function
        
        Public Function SelecccionarUsuarioAsync() As System.Threading.Tasks.Task(Of Entidades.UsuarioENT()) Implements ServicioLogin.IUsuarioWcf.SelecccionarUsuarioAsync
            Return MyBase.Channel.SelecccionarUsuarioAsync
        End Function
    End Class
End Namespace
