'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioActividadDetalleInforme
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioActividadDetalleInforme.IActividadDetalleInformeWcf")>  _
    Public Interface IActividadDetalleInformeWcf
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodos() As Entidades.ActividadDetalleInformeENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/SeleccionarTodos", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/SeleccionarTodosResponse")>  _
        Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadDetalleInforme", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadDetalleInformeRespo"& _ 
            "nse")>  _
        Function BuscarActividadDetalleInforme(ByVal campo As String, ByVal texto As String) As Entidades.ActividadDetalleInformeENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadDetalleInforme", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadDetalleInformeRespo"& _ 
            "nse")>  _
        Function BuscarActividadDetalleInformeAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadFecha", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadFechaResponse")>  _
        Function BuscarActividadFecha(ByVal fechaInicio As Date, ByVal fechaFinal As Date) As Entidades.ActividadDetalleInformeENT()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadFecha", ReplyAction:="http://tempuri.org/IActividadDetalleInformeWcf/BuscarActividadFechaResponse")>  _
        Function BuscarActividadFechaAsync(ByVal fechaInicio As Date, ByVal fechaFinal As Date) As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IActividadDetalleInformeWcfChannel
        Inherits ServicioActividadDetalleInforme.IActividadDetalleInformeWcf, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ActividadDetalleInformeWcfClient
        Inherits System.ServiceModel.ClientBase(Of ServicioActividadDetalleInforme.IActividadDetalleInformeWcf)
        Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SeleccionarTodos() As Entidades.ActividadDetalleInformeENT() Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.SeleccionarTodos
            Return MyBase.Channel.SeleccionarTodos
        End Function
        
        Public Function SeleccionarTodosAsync() As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT()) Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.SeleccionarTodosAsync
            Return MyBase.Channel.SeleccionarTodosAsync
        End Function
        
        Public Function BuscarActividadDetalleInforme(ByVal campo As String, ByVal texto As String) As Entidades.ActividadDetalleInformeENT() Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.BuscarActividadDetalleInforme
            Return MyBase.Channel.BuscarActividadDetalleInforme(campo, texto)
        End Function
        
        Public Function BuscarActividadDetalleInformeAsync(ByVal campo As String, ByVal texto As String) As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT()) Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.BuscarActividadDetalleInformeAsync
            Return MyBase.Channel.BuscarActividadDetalleInformeAsync(campo, texto)
        End Function
        
        Public Function BuscarActividadFecha(ByVal fechaInicio As Date, ByVal fechaFinal As Date) As Entidades.ActividadDetalleInformeENT() Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.BuscarActividadFecha
            Return MyBase.Channel.BuscarActividadFecha(fechaInicio, fechaFinal)
        End Function
        
        Public Function BuscarActividadFechaAsync(ByVal fechaInicio As Date, ByVal fechaFinal As Date) As System.Threading.Tasks.Task(Of Entidades.ActividadDetalleInformeENT()) Implements ServicioActividadDetalleInforme.IActividadDetalleInformeWcf.BuscarActividadFechaAsync
            Return MyBase.Channel.BuscarActividadFechaAsync(fechaInicio, fechaFinal)
        End Function
    End Class
End Namespace
